appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: spLIbDQMT3DmqOcpUxxHbw3mdAqBtzA375gcbyezzjuff+A3yxlovWu8q2WuS81O/sUpxI7gp/a3COt1wwQqmIMHiqjQeL17DSz9rj4rPqZi8Y1jqhX7gaey7dZbmMjOp6CNnYqn7ps9VJi+w0Fe7y8UGFPWYlAC1pkduLAjdWjdstFoNfzeOdoE8fYUMF4n0vE861AHDyOpamyAEHdYEVtcYWjzxJoJHmZXtsfTp086SHy649Rd8twiyTmzPdZKI/BXkIV1EdhfzidY66Q+inMpJmgPD2ymSZu6PHrtb3u7XBLsxHjZS1opD4fWpJEdK1r3I5kUFOSuFUVXoFx3HsIPkW6I9E/+u9unErS1Xn0FTA82Nz9E5tx61zb80SVMkR5PGxpdy5pBuCzje4Hjj3mFxvih+PHY6VD1LsMdHrKs2tLLjrnmfyqKo8KAKYCdI0jSrqqpanqhMhoHDzGCHLEZmCpPy1I/03TT58HEXalhFmieJ0BFOUXNphz5BhtFXkYOfzbbjMTioErY8Ga0U1nw2/WFC45kj7DAbmIXO6Kv/qF1OeFM0wEXJ+TymsuPMYWjXA4BhuCphyGKdoAoyiuubX1iTHqA83Qg4SyOGDBEj3O5aOq0p3H6jqC0GagmW0Aw83r3qza7b3z5SeeSZqbs7dgcKuLp0qkprIYuMJg=}
provider:
  win: azure
conda_forge_output_validation: true
